#!/bin/bash
# Levanta n nodos, simulando lo realizado por el .fog pero localmente.
# Esto no incluye ningun tipo de monitoreo ya que las cosas andan localmente
#
# Parametros:
# - Numero de nodos (sin incluir el del historial) que desee levantar
# - Numero de nodos con selfish mining que desee levantar (este numero debe ser menor al de arriba)

# FIXME: Considerar reportar aca algo respecto del estado de los nodos
# FIXME: Es una paja correr este script porque no se tiene nada de output y no es tan claras las cosas que correr... habría que ver de mejorar eso en algún momento que esto no lo estoy usando ahora

# FIXME: Mejorar este mecanismo
# Hack que permite ver facilmente si la pechee o no cambiando este script, solo tengo que cambiar esta variable para que haya mayor logging
debug=false
scriptdir=/Users/mpizzagali/Tesis/btc-core/tooling/ejecucion-nodos
datadir=$scriptdir/.exec-results/data-0
addressesdir=$scriptdir/.exec-results
logdir=$scriptdir/logs


if $debug; then
    set -x
fi

# Parametros
numnodes=${1:-1}
runName=${2:-"test"}
numselfishnodes=${3:-0}
startLogAt=$(($numnodes*2400))

# runlogdir=$scriptdir/logs/$(date +'%Y%m%d%H%M%S')-$runName

# echo "Going to create the folder $runlogdir to save the results inside for nodes $numnodes"

# mkdir $runlogdir

echo $startLogAt
