#!/bin/bash
# Levanta n nodos, simulando lo realizado por el .fog pero localmente.
# Esto no incluye ningun tipo de monitoreo ya que las cosas andan localmente
#
# Parametros:
# - Numero de nodos (sin incluir el del historial) que desee levantar
# - Numero de nodos con selfish mining que desee levantar (este numero debe ser menor al de arriba)

# FIXME: Considerar reportar aca algo respecto del estado de los nodos
# FIXME: Es una paja correr este script porque no se tiene nada de output y no es tan claras las cosas que correr... habría que ver de mejorar eso en algún momento que esto no lo estoy usando ahora

# FIXME: Mejorar este mecanismo
# Hack que permite ver facilmente si la pechee o no cambiando este script, solo tengo que cambiar esta variable para que haya mayor logging
debug=false

if $debug; then
    set -x
fi

# Parametros
numnodes=${1:-1}
startLogAt=$(($numnodes*2400))
numselfishnodes=${2:-0}
runName=${3:-"test"}
mode=${4:-"free"}
traceFileIn=${5:-""}

# Constantes
gobin=go
scriptdir=/Users/mpizzagali/Tesis/btc-core/tooling/ejecucion-nodos
datadir=$scriptdir/.exec-results/data-0
addressesdir=$scriptdir/.exec-results
logdir=$scriptdir/logs

runlogdir=$scriptdir/logs/$(date +'%Y%m%d%H%M%S')-$runName

echo "Going to create the folder $runlogdir to save the results inside for nodes $numnodes"

mkdir $runlogdir

echo "$mode"

if [ "$mode" = "free" ]; then
    echo "Disparo el motor que genero bloques en cada uno de los nodos"
elif [ "$mode" = "trace" ]; then
    echo "Muevo la traza de entrada a la carpeta de los logs y la renombro trace.in"
    cp $traceFileIn $runlogdir/trace.in
else 
    echo "Invalid mode"
fi

echo "Hola"