#!/bin/bash
# Levanta n nodos, simulando lo realizado por el .fog pero localmente.
# Esto no incluye ningun tipo de monitoreo ya que las cosas andan localmente
#
# Parametros:
# - Numero de nodos (sin incluir el del historial) que desee levantar
# - Numero de nodos con selfish mining que desee levantar (este numero debe ser menor al de arriba)

# FIXME: Considerar reportar aca algo respecto del estado de los nodos
# FIXME: Es una paja correr este script porque no se tiene nada de output y no es tan claras las cosas que correr... habría que ver de mejorar eso en algún momento que esto no lo estoy usando ahora

# FIXME: Mejorar este mecanismo
# Hack que permite ver facilmente si la pechee o no cambiando este script, solo tengo que cambiar esta variable para que haya mayor logging
debug=false

if $debug; then
    set -x
fi

# Parametros
numnodes=${1:-1}
numselfishnodes=${2:-0}

# Constantes
scriptdir=$(dirname $(readlink -f $0))
datadir=$(dirname $(readlink -f $0))/.exec-results/data-0
addressesdir=$(dirname $(readlink -f $0))/.exec-results

echo "Borramos los archivos de log de corridas viejas"
find . -name 'btcCoreLogN*' -delete

echo "Empiezo $numnodes nodo(s) BTC"
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    if (($nodeId<$numselfishnodes)); then
        bash $scriptdir/invokeBitcoin.sh $nodeId -dificulta=0 -dbcache=3072 -selfish-mine
    else
        bash $scriptdir/invokeBitcoin.sh $nodeId -dificulta=0 -dbcache=3072
    fi
done
sleep 30s # Esperamos a que termine el booteo

echo "Esperamos a que los nodos se estabilicen"
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    /usr/local/go/bin/go run $scriptdir/semaphore.go $nodeId
done

echo "Conectamos los nodos cada uno con el otro (por ahora en forma de clique)"
for (( node1Id=0; node1Id<$numnodes-1; node1Id++ ))
do
    for (( node2Id=node1Id+1; node2Id<$numnodes; node2Id++ ))
    do
        bash $scriptdir/connectNodes.sh $node1Id $node2Id localhost
    done
done

echo "Comienzo el nodo que genera el historial y lo conecto al resto de los nodos"
bash $scriptdir/invokeBitcoin.sh $numnodes -dificulta=0 -dbcache=3072
sleep 30s
/usr/local/go/bin/go run $scriptdir/semaphore.go $numnodes
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    bash $scriptdir/connectNodes.sh $nodeId $numnodes localhost
done

echo "Genero addresses para darle fondos a cada uno de los nodos"
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    rm -f $addressesdir/addrN$nodeId
done
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    bash $scriptdir/bitcoindo.sh $nodeId getnewaddress > $addressesdir/addrN$nodeId
    bash $scriptdir/bitcoindo.sh $nodeId getnewaddress >> $addressesdir/addrN$nodeId
done

echo "Generamos una blockchain inicial"
/usr/local/go/bin/go run $scriptdir/generateBlockchain.go $numnodes
sleep 30s

echo "Esperamos que los nodos se estabilicen despues de recibir la blockchain inicial"
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    /usr/local/go/bin/go run $scriptdir/semaphore.go $nodeId
done

echo "Mato al nodo del historial"
bash $scriptdir/bitcoindo.sh $numnodes stop
sleep 1m

# FIXME: Tengo algun forma de ver las cosas que loggea esto?
echo "Genero bloques y txs en cada uno de los nodos"
nodeshp=$(bc -l <<< "1.0/$numnodes")
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    /usr/local/go/bin/go run $scriptdir/launcher.go /usr/local/go/bin/go run $scriptdir/testEngine.go $nodeId $nodeshp
    sleep 1s
done

# Paro a los nodos BTC ante un SIGINT o un SIGTERM
stopAllBTCNodes() {
    echo 'Señal de matar a los nodos recibida, matando a los BTC nodes levantados...'
    for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
    do
        bash $scriptdir/bitcoindo.sh $nodeId stop
    done
    sleep 1m

    if $debug; then
        set +x
    fi
}
trap stopAllBTCNodes SIGINT SIGTERM
sleep infinity
