#!/bin/bash
# Levanta n nodos, simulando lo realizado por el .fog pero localmente.
# Esto no incluye ningun tipo de monitoreo ya que las cosas andan localmente
#
# Parametros:
# - Numero de nodos (sin incluir el del historial) que desee levantar
# - Numero de nodos con selfish mining que desee levantar (este numero debe ser menor al de arriba)

# FIXME: Considerar reportar aca algo respecto del estado de los nodos
# FIXME: Es una paja correr este script porque no se tiene nada de output y no es tan claras las cosas que correr... habría que ver de mejorar eso en algún momento que esto no lo estoy usando ahora

# FIXME: Mejorar este mecanismo
# Hack que permite ver facilmente si la pechee o no cambiando este script, solo tengo que cambiar esta variable para que haya mayor logging
debug=false

if $debug; then
    set -x
fi

# Parametros
numnodes=${1:-1}
numselfishnodes=${2:-0}

# Constantes
gobin=go
scriptdir=/Users/mpizzagali/Tesis/btc-core/ejecucion-nodos
datadir=$scriptdir/.exec-results/data-0
addressesdir=$scriptdir/.exec-results

# FIXME: Tengo algun forma de ver las cosas que loggea esto?
echo "Genero bloques y txs en cada uno de los nodos"
echo "Mentira no voy a correr nada, ya podes cortar esto..."
nodeshp=$(bc -l <<< "1.0/$numnodes")
for (( nodeId=0; nodeId<$numnodes; nodeId++ ))
do
    $gobin run $scriptdir/launcher.go $gobin run $scriptdir/testRandom.go $nodeId $nodeshp
    sleep 1s
done
